### ISSUE TITLE
ultibo branch review

### ISSUE THREAD

**Issue by markfirmware** [markfirmware/tetris#1]
Working in the branch https://github.com/markfirmware/tetris/tree/ultibo
All of this work is a disposable draft.

@andrewrk - before going further I'd like to know whether these are in line with your sense of simplicity:

* core_tetris references in main.zig
* the use of callbacks for rendering rectangles, triangles, and text

Summary:

1. I moved a lot of main.zig into coretetris.zig. This then requires core_tetris. prefixes in main.zig:
https://github.com/markfirmware/tetris/blob/550ebb89002ed7a4d88ad7e547d9286b9a0f227c/src/main.zig#L115-L118
2. Tetris is already in the callback business with glfw errors/keypresses so callbacks are used to link the three rendering functions (rectangles, triangles, text:)
https://github.com/markfirmware/tetris/blob/550ebb89002ed7a4d88ad7e547d9286b9a0f227c/src/main.zig#L35
3. I moved the glfw rendering elements from the Tetris struct to a Display struct:
https://github.com/markfirmware/tetris/blob/550ebb89002ed7a4d88ad7e547d9286b9a0f227c/src/main.zig#L20-L25
4. I added buildultibo.zig which build.zig uses to build the ultibo version. There is zig build ultibo-qemu and zig build play-ultibo-qemu. Rectangles are working (without alpha channel) and keys are working (without arrows - use awsz keys instead.) Triangles (particles) and text (2d pixmaps) are not yet addressed. ultibomainpas.pas is the ultibo main program and [ultibomainzig.zig](https://github.com/markfirmware/tetris/blob/ultibo/src/ultibomainzig.zig) is the ultibo equivalent of glfw main.zig.

**Comment by andrewrk** [comment]
Why not mv ultibobuild.zig to build.zig in the ultibo branch?

There are some things to fix in the build script that would make it easier for me to play with it:

Instead of:

```zig
    const zigmain = b.addSystemCommand([][]const u8 {
"zig", "build-obj", "-target", "armv7-freestanding-gnueabihf",
...
```

There is API for this directly:

```zig
const arch = builtin.Arch{ .arm = builtin.Arch.Arm32.v7 };
const zigmain  = b.addObject("ultibomainzig", "ultibomainzig.zig");
zigmain.setTarget(arch, .freestanding, .gnueabihf);
zigmain.addIncludeDir("subtree/ultibohub/API/include");
...
```

Without this change, it's using the wrong zig version on my system so I cannot test it.

Note that `addSystemCommand` is probably incorrect if you are invoking zig or invoking something you just built with zig. For example:

```zig
    const build_client_command = b.addSystemCommand([][]const u8 {
        "zig", "build-exe", "--library", "c", "client.zig"
});
```

Use `b.addExecutable` instead.

```zig
    const run_client_command = b.addSystemCommand([][]const u8 {
        "./client",
});
```

Use `client.run()` instead, like this:
https://github.com/andrewrk/tetris/blob/24d9f07501e71a235f997af5658432ac93f7621a/build.zig#L27

**Comment by markfirmware** [comment]
The ultibo branch has the glfw main.zig refactored so build.zig still builds the refactored main.zig in that branch, and I just have (build.zig/fn build) call (buildultibo.zig/fn build) to add in the steps for ultibo. This is to clearly separate the refactored glfw from ultibo during this phase of development.

Right now I’m stuck on getting the full path to the addObject artifact which I need for moving the .o to a place where the linker for ultibo can find it.

**Comment by andrewrk** [comment]
In this case you can use
```zig
     exe.setOutputDir("zig-cache");
```
and then later
```zig
exe.getOutputPath(),
```

You can see an example here: https://github.com/andrewrk/clashos/blob/91f45cff49128b3322f98cc78ed08df5bcec35cb/build.zig#L24

Or you can use the `install` target.

**Comment by markfirmware** [comment]
FYI I made a release that runs on rpi's. https://github.com/markfirmware/tetris/releases The arrow keys work but there are yet no particles, falling blocks, nor text. There is bad flicker which I will address next (the ultibo frame buffer has some buffering options.)

Ok, I reworked buildultibo.zig.
https://github.com/markfirmware/tetris/blob/95f6608331c13a1eb8c894f1c4db8cd34ff00520/buildultibo.zig#L15-L29

To build the ultibo kernel you need to have the ultibo fpc compiler and linker installed. There is an ultibo installer script for debian but it occurs to me that you work on nixos. I can update and test a docker installation of the ultibo fpc compiler and linker that zig build will use - would you like me to do that?

**Comment by markfirmware** [comment]
Superseded by #9
